 name: release-pr
 
 on:
   create:
     branch:
       - release
 
 jobs:
   job:
     runs-on: ubuntu-18.04
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0 # Need to fetch merge history
 
       - name: Set up Ruby
         uses: actions/setup-ruby@v1
         with:
           ruby-version: 2.7.x
 
       - name: Create a release pull request
         env:
           GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GIT_PR_RELEASE_BRANCH_PRODUCTION: master
           GIT_PR_RELEASE_BRANCH_STAGING: release
           GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template
         run: |
           gem install -N git-pr-release
           git-pr-release